### ISSUE TITLE
Want to adopt sarge feedstock?

### ISSUE THREAD

**Issue by takluyver** [conda-forge/sarge-feedstock#2]
We packaged sarge for conda because a package we wrote depended on it. Since then, we dropped the dependency and made it work with plain subprocess. So we no longer have an interest in maintaining the sarge package. Anyone who does have an interest in it, please get in touch to take over maintenance.

**Comment by igortg** [comment]
I'd be interested

**Comment by takluyver** [comment]
OK by me - do you want to make a PR adding yourself to the maintainers list?

**Comment by igortg** [comment]
Yup, I'll take the time to also update to v0.1.6
